VIEWPORT_WIDTH = 800
VIEWPORT_HEIGHT = 600
SIZE_COEFFICIENT = 0.8
VP_IN_START_POSITION = (0, 0)
VP_IN_WIDTH = VIEWPORT_WIDTH * (1 - SIZE_COEFFICIENT)

VP_OUT_START_POSITION = (VP_IN_WIDTH + 100, 0)
VP_OUT_WIDTH = VIEWPORT_WIDTH * SIZE_COEFFICIENT - 200

INPUT_PLAYER_WIDTH = 100

PRIMARY_WINDOW_TAG = 'PRIMARY_WINDOW'
BTN_SAVE_TAG = 'BTN_SAVE'
LABEL_TEAM1_TITLE_TAG = 'LABEL_TEAM1_TITLE'
BTN_SELECT_FILE_TAG = 'BTN_CHOOSE_FILE'
FILE_SELECTOR_TAG = 'FILE_SELECTOR'
ERROR_POPUP_TAG = 'ERROR_POPUP'

TEAM_PLAYERS_AMOUNT = 5

team1_player_tags = [f'TEAM1_PLAYER{i}_NICKNAME' for i in range(1, 6)]
team2_player_tags = [f'TEAM2_PLAYER{i}_NICKNAME' for i in range(1, 6)]

PROGRESS_BAR_TAG = 'PROGRESS_BAR'
