VIEWPORT_WIDTH = 800
VIEWPORT_HEIGHT = 600

VP_IN_START_POSITION = (0, 0)
VP_OUT_START_POSITION = (VIEWPORT_WIDTH / 2, 0)

VP_IN_WIDTH = VIEWPORT_WIDTH / 2
VP_OUT_WIDTH = VIEWPORT_WIDTH / 2

PRIMARY_WINDOW_TAG = 'PRIMARY_WINDOW'
BTN_SAVE_TAG = 'BTN_SAVE'
LABEL_TEAM1_TITLE_TAG = 'LABEL_TEAM1_TITLE'
BTN_SELECT_FILE_TAG = 'BTN_CHOOSE_FILE'
FILE_SELECTOR_TAG = 'FILE_SELECTOR'

TEAM_PLAYERS_AMOUNT = 5

team1_player_tags = [f'TEAM1_PLAYER{i}_NICKNAME' for i in range(1, 6)]
team2_player_tags = [f'TEAM2_PLAYER{i}_NICKNAME' for i in range(1, 6)]

# TEAM1_PLAYER1_NICKNAME_TAG = 'TEAM1_PLAYER1_NICKNAME'
# TEAM1_PLAYER2_NICKNAME_TAG = 'TEAM1_PLAYER2_NICKNAME'
# TEAM1_PLAYER3_NICKNAME_TAG = 'TEAM1_PLAYER3_NICKNAME'
# TEAM1_PLAYER4_NICKNAME_TAG = 'TEAM1_PLAYER4_NICKNAME'
# TEAM1_PLAYER5_NICKNAME_TAG = 'TEAM1_PLAYER5_NICKNAME'
#
# TEAM2_PLAYER1_NICKNAME_TAG = 'TEAM1_PLAYER1_NICKNAME'
# TEAM2_PLAYER2_NICKNAME_TAG = 'TEAM1_PLAYER2_NICKNAME'
# TEAM2_PLAYER3_NICKNAME_TAG = 'TEAM1_PLAYER3_NICKNAME'
# TEAM2_PLAYER4_NICKNAME_TAG = 'TEAM1_PLAYER4_NICKNAME'
# TEAM2_PLAYER5_NICKNAME_TAG = 'TEAM1_PLAYER5_NICKNAME'
